name: Keep Render Server Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes UTC
  workflow_dispatch:        # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Book Barter Backend
        run: curl https://book-barter-backend.onrender.com/api/books/explore
